Repository puppetlabs/bolt, pull requests merged in 2018-10, with the labels that each got.

#670 (BOLT-863) Update acceptance tests for ApplyResult
  acceptance/tests/apply_ssh.rb
  acceptance/tests/apply_winrm.rb
Labels: Do Not Merge

#684 (BOLT-898) Include agent facts in apply_prep
  libexec/custom_facts.rb
  spec/fixtures/apply/prep/plans/init.pp
  spec/integration/apply_spec.rb
Labels: Bug

#683 (BOLT-900) Allow deprecations in functions used in a manifest block
  lib/bolt/catalog.rb
  spec/fixtures/apply/basic/manifests/strict.pp
  spec/fixtures/apply/basic/manifests/strict_variables.pp
  spec/fixtures/apply/basic/plans/strict.pp
  spec/fixtures/apply/basic/plans/strict_variables.pp
  spec/integration/apply_compile_spec.rb
Labels: Bug

#539 (BOLT-191) Support uploading directories
  lib/bolt/cli.rb
  lib/bolt/transport/local.rb
  lib/bolt/transport/orch.rb
  lib/bolt/transport/ssh/connection.rb
  spec/bolt/cli_spec.rb
  spec/bolt/transport/local_spec.rb
  spec/bolt/transport/orch_spec.rb
  spec/bolt/transport/ssh_spec.rb
  spec/bolt/transport/winrm_spec.rb
Labels: Feature Request
