Repository puppetlabs/bolt, pull requests merged in 2019-10, with the labels that each got.

#1334 (GH-1314) Auto-generate command reference docs
  .gitignore
  .travis.yml
  Rakefile
  documentation/bolt_command_reference.md
  documentation/bolt_command_reference.md.erb
Labels: Docs

#1349 (maint) Maintain ruby 2.3 compatibility by not using Dir.children
  lib/bolt/module.rb
Labels: Bug

#1354 (packaging) Ship Puppetfile with bolt gem
  bolt.gemspec
Labels: Work in Progress

#1355 (GH-1269) Require argument for --password and --sudo-password options
  CHANGELOG.md
  lib/bolt/bolt_option_parser.rb
  lib/bolt/plugin/prompt.rb
  spec/bolt/cli_spec.rb
  spec/bolt/plugin/prompt_spec.rb
Labels: 2.0, Feature

#1364 (GH-1162) Expand configured paths relative to Boltdir
  CHANGELOG.md
  Puppetfile
  documentation/bolt_configuration_options.md
  documentation/configuring_bolt.md
  documentation/using_plugins.md
  lib/bolt/cli.rb
  lib/bolt/config.rb
  lib/bolt/puppetdb/config.rb
  spec/bolt/config_spec.rb
  spec/bolt/inventory_spec.rb
  spec/bolt/puppetdb/config_spec.rb
  spec/fixtures/configs/future.yml
Labels: Do Not Merge
