Repository puppetlabs/bolt, pull requests merged in 2020-02, with the labels that each got.

#1592 (GH-1584) Add options to Bolt plan functions documentation
  Rakefile
  bolt-modules/boltlib/lib/puppet/functions/add_facts.rb
  bolt-modules/boltlib/lib/puppet/functions/add_to_group.rb
  bolt-modules/boltlib/lib/puppet/functions/apply_prep.rb
  bolt-modules/boltlib/lib/puppet/functions/catch_errors.rb
  bolt-modules/boltlib/lib/puppet/functions/fail_plan.rb
  bolt-modules/boltlib/lib/puppet/functions/get_resources.rb
  bolt-modules/boltlib/lib/puppet/functions/get_target.rb
  bolt-modules/boltlib/lib/puppet/functions/get_targets.rb
  bolt-modules/boltlib/lib/puppet/functions/puppetdb_fact.rb
  bolt-modules/boltlib/lib/puppet/functions/remove_from_group.rb
  bolt-modules/boltlib/lib/puppet/functions/resolve_references.rb
  bolt-modules/boltlib/lib/puppet/functions/run_command.rb
  bolt-modules/boltlib/lib/puppet/functions/run_plan.rb
  bolt-modules/boltlib/lib/puppet/functions/run_script.rb
  bolt-modules/boltlib/lib/puppet/functions/run_task.rb
  bolt-modules/boltlib/lib/puppet/functions/set_config.rb
  bolt-modules/boltlib/lib/puppet/functions/set_feature.rb
  bolt-modules/boltlib/lib/puppet/functions/set_var.rb
  bolt-modules/boltlib/lib/puppet/functions/upload_file.rb
  bolt-modules/boltlib/lib/puppet/functions/wait_until_available.rb
  bolt-modules/boltlib/lib/puppet/functions/without_default_logging.rb
  bolt-modules/ctrl/lib/puppet/functions/ctrl/do_until.rb
  bolt-modules/file/lib/puppet/functions/file/exists.rb
  bolt-modules/file/lib/puppet/functions/file/join.rb
  bolt-modules/file/lib/puppet/functions/file/read.rb
  bolt-modules/file/lib/puppet/functions/file/readable.rb
  bolt-modules/out/lib/puppet/functions/out/message.rb
  bolt-modules/system/lib/puppet/functions/system/env.rb
  documentation/reference.md.erb
Labels: Docs

#1546 (maint) Bump required ruby version to 2.5
  .rubocop.yml
  bolt-modules/boltlib/lib/puppet/functions/apply_prep.rb
  bolt.gemspec
  lib/bolt/applicator.rb
  lib/bolt/executor.rb
  lib/bolt/inventory/group.rb
  lib/bolt/module.rb
  lib/bolt/pal.rb
  lib/bolt/pal/yaml_plan/step/resources.rb
  lib/bolt/transport/local/shell.rb
  lib/bolt/transport/orch.rb
  lib/bolt/transport/winrm/connection.rb
  lib/bolt/util.rb
  lib/bolt_server/transport_app.rb
  spec/bolt/pal/yaml_plan/evaluator_spec.rb
  spec/bolt_server/file_cache_spec.rb
Labels: 2.0

#1565 (GH-1536) Add Bolt 2.0 breaking changes to CHANGELOG
  CHANGELOG.md
Labels: 2.0

#1610 Docs reorg - WIP
  documentation/applying_manifest_blocks.md
  documentation/bolt.ditamap
  documentation/bolt.md
  documentation/bolt_examples.md
  documentation/bolt_installing.md
  documentation/bolt_installing_modules.md
  documentation/bolt_options.md
  documentation/bolt_project_directories.md
  documentation/bolt_running_plans.md
  documentation/bolt_running_tasks.md
  documentation/bolt_versioning.md
  documentation/configuring_bolt.md
  documentation/directory_structure.md
  documentation/getting_started_with_bolt.md
  documentation/inspecting_plans.md
  documentation/inspecting_tasks.md
  documentation/inventory_file_v2.md
  documentation/migrating_inventory_files.md
  documentation/plans.md
  documentation/reference.md.erb
  documentation/running_bolt.md
  documentation/running_bolt_commands.md
  documentation/running_bolt_in_docker.md
  documentation/tasks.md
  documentation/writing_tasks_and_plans.md
Labels: Docs

#1627 (maint) Validate inventory more efficiently
  CHANGELOG.md
  lib/bolt/inventory/inventory.rb
  spec/bolt/inventory/inventory_spec.rb
  spec/integration/inventory_spec.rb
Labels: Bug
