Repository puppetlabs/bolt, pull requests merged in 2020-01, with the labels that each got.

#1495 (GH-837) Add `file::join` plan function
  CHANGELOG.md
  bolt-modules/file/lib/puppet/functions/file/join.rb
  bolt-modules/file/spec/functions/file/join_spec.rb
Labels: Feature

#1471 (GH-1464) Update Version 2 inventory file and plugins docs
  documentation/bolt.ditamap
  documentation/inventory_file_v2.md
  documentation/migrating_inventory_files.md
  documentation/using_plugins.md
Labels: Docs

#1522 (GH-1464) Move target creation and modification docs
  documentation/writing_plans.md
Labels: Docs

#1501 (GH-1481) Add deprecation message for Target.new(<uri>, <options>)
  CHANGELOG.md
  lib/bolt/target.rb
Labels: Do Not Merge

#1530 (GH-1315) Auto-generate configuration options docs
  .gitignore
  .rubocop.yml
  Rakefile
  documentation/bolt.ditamap
  documentation/bolt_configuration_options.md
  documentation/bolt_configuration_reference.md.erb
  lib/bolt/config.rb
  lib/bolt/transport/docker.rb
  lib/bolt/transport/local.rb
  lib/bolt/transport/local_windows.rb
  lib/bolt/transport/orch.rb
  lib/bolt/transport/remote.rb
  lib/bolt/transport/ssh.rb
  lib/bolt/transport/winrm.rb
Labels: Docs

#1513 (GH-1208) Ensure Puppet agent version with apply_prep
  CHANGELOG.md
  Puppetfile
  bolt-modules/boltlib/lib/puppet/functions/apply_prep.rb
  bolt-modules/boltlib/spec/functions/apply_prep_spec.rb
  spec/bolt_spec/run_spec.rb
  spec/integration/apply_spec.rb
Labels: Feature
