Repository puppetlabs/bolt, pull requests merged in 2020-04, with the labels that each got.

#1691 (GH-1685) Add data type functions reference docs
  documentation/applying_manifest_blocks.md
  documentation/bolt.ditamap
  documentation/bolt_types_reference.md
  documentation/writing_plans.md
Labels: Do Not Merge

#1704 (Docs) Add links to config from inventory docs
  documentation/inventory_file_v2.md
Labels: Docs

#1711 (Docs) Adding blog post on Bolt plans
  documentation/bolt.md
Labels: Docs

#1728 Make dependency of apply_prep before apply clear
  documentation/applying_manifest_blocks.md
Labels: Docs

#1696 Bolt::Util.deep_clone fails with frozen hashes
  lib/bolt/util.rb
  spec/bolt/util_spec.rb
Labels: Bug

#1746 (docs) Plugins edits
  documentation/using_plugins.md
Labels: Docs
