Repository puppetlabs/bolt, pull requests merged in 2020-11, with the labels that each got.

#2316 (Docs) Update choco package doc
  documentation/automating_windows_targets.md
  documentation/tig_stack.md
Labels: Docs

#2341 (GH-2210) Configure 'modules' with 'bolt project init'
  lib/bolt/cli.rb
  lib/bolt/project_manager.rb
  lib/bolt/project_manager/config_migrator.rb
  lib/bolt/project_manager/inventory_migrator.rb
  lib/bolt/project_manager/migrator.rb
  lib/bolt/project_manager/module_migrator.rb
  lib/bolt/project_migrator.rb
  spec/bolt/cli_spec.rb
  spec/bolt/project_manager/config_migrator_spec.rb
  spec/bolt/project_manager/inventory_migrator_spec.rb
  spec/bolt/project_manager/module_migrator_spec.rb
  spec/bolt/project_manager_spec.rb
  spec/bolt/project_migrator_spec.rb
  spec/integration/project_manager_spec.rb
  spec/lib/bolt_spec/project.rb
Labels: Blocked

#2161 (PUP-10653) Remove dependency on win32/dir
  lib/bolt/config.rb
  lib/bolt/puppetdb/config.rb
Labels: Bolt 3.0, Do Not Merge, Puppet 7

#2367 (GH-2323)(Docs) Finalize module docs
  documentation/applying_manifest_blocks.md
  documentation/bolt.ditamap
  documentation/bolt_installing_modules.md
  documentation/bolt_running_plans.md
  documentation/bolt_running_tasks.md
  documentation/developer_updates.md
  documentation/getting_started_with_bolt.md
  documentation/inspecting_tasks.md
  documentation/managing_modules.md
  documentation/migrating_inventory_files.md
  documentation/module_structure.md
  documentation/modules.md
  documentation/projects.md
  documentation/troubleshooting.md
Labels: Docs
