Repository puppetlabs/bolt, pull requests merged in 2020-08, with the labels that each got.

#2048 (Docs) Clarify inventory name, alias, uri
  documentation/inventory_file_v2.md
Labels: Docs

#2049 PowerShell Code Formating and Style
  .github/workflows/pwsh.yaml
  pwsh_module/command.tests.ps1
  pwsh_module/pwsh_bolt.psm1.erb
  pwsh_module/pwsh_bolt_internal.ps1
  rakelib/pwsh.rake
Labels: Feature

#2066 (Docs) Change link to shim doc
  documentation/bolt.ditamap
  documentation/bolt_configure_orchestrator.md
Labels: Docs

#2065 (GH-1999) Unexperimentalify project docs
  documentation/README.md
  documentation/applying_manifest_blocks.md
  documentation/bolt.ditamap
  documentation/bolt_examples.md
  documentation/bolt_installing_modules.md
  documentation/bolt_known_issues.md
  documentation/bolt_options.md
  documentation/bolt_project_directories.md
  documentation/bolt_running_plans.md
  documentation/bolt_running_tasks.md
  documentation/bolt_types_reference.md
  documentation/configuring_bolt.md
  documentation/experimental_features.md
  documentation/getting_started_with_bolt.md
  documentation/module_structure.md
  documentation/projects.md
  documentation/running_bolt_commands.md
  documentation/templates/bolt_project_reference.md.erb
  documentation/templates/bolt_transports_reference.md.erb
  documentation/writing_yaml_plans.md
Labels: Docs

#2071 (Docs) Overriding a packaged module
  documentation/bolt_installing_modules.md
  documentation/module_structure.md
Labels: Docs

#2114 (Docs) Installing modules shuffle and edit
  documentation/bolt_installing_modules.md
  documentation/troubleshooting.md
Labels: Docs

#2113 (Docs) Update side nav titles for plans and tasks
  documentation/bolt.ditamap
Labels: Docs

#2080 (GH-2051) Always set `bolt_project` Puppet setting
  bolt-modules/boltlib/lib/puppet/functions/download_file.rb
  bolt-modules/boltlib/spec/functions/download_file_spec.rb
  bolt-modules/dir/lib/puppet/functions/dir/children.rb
  bolt-modules/dir/spec/functions/dir/children_spec.rb
  bolt.gemspec
  lib/bolt/applicator.rb
  lib/bolt/catalog.rb
  lib/bolt/pal.rb
  lib/bolt/project.rb
  spec/bolt/catalog_spec.rb
  spec/bolt/cli_spec.rb
  spec/bolt/pal_spec.rb
Labels: Blocked, Do Not Merge
