Repository puppetlabs/bolt, pull requests merged in 2021-01, with the labels that each got.

#2501 (GH-2013) Update docs on PowerShell execution policy
  documentation/bolt_installing.md
Labels: Docs

#2496 (GH-2478) Support module-install config when resolving modules
  bolt.gemspec
  documentation/bolt_installing_modules.md
  documentation/bolt_known_issues.md
  lib/bolt/cli.rb
  lib/bolt/module_installer/resolver.rb
  spec/integration/module_installer_spec.rb
Labels: Blocked, Do Not Merge

#2541 (Docs) Fixes #2539 and #2534
  documentation/bolt_configure_orchestrator.md
  documentation/bolt_installing.md
Labels: Docs

#2564 (GH-2562) Fix linking issues on plugins pages
  documentation/inventory_file_v2.md
  documentation/using_plugins.md
Labels: Docs

#2277 (GH-2111) Shadow fact/variable collisions in PAL catalog compiler
  lib/bolt/catalog.rb
  spec/bolt/catalog_spec.rb
  spec/fixtures/apply/basic/plans/collisions.pp
  spec/integration/apply_compile_spec.rb
Labels: Bolt 3.0

#2578 (Docs) 3.0 docs updates - modulepath, bolt.yaml
  documentation/README.md
  documentation/configuring_bolt.md
  documentation/experimental_features.md
  documentation/inventory_file_v2.md
  documentation/module_structure.md
  documentation/projects.md
  documentation/upgrading_to_bolt_3.md
Labels: Docs

#2599 (Docs) Minor changes for 3.0
  documentation/bolt_installing.md
  documentation/configuring_bolt.md
  documentation/templates/privilege_escalation.md.erb
Labels: Bolt 3.0, Docs
